;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	LaTeX-babel-insert-hyphen
	LaTeX-insert-item
	LaTeX-insert-left-brace
	TeX-insert-backslash
	TeX-insert-dollar
	TeX-insert-sub-or-superscript
	abort-recursive-edit
	backward-kill-sentence
	c-electric-paren
	c-electric-semi&comma
	c-indent-line-or-region
	comment-dwim
	comment-line
	dired-do-flagged-delete
	dired-flag-file-deletion
	dired-next-line
	electric-newline-and-maybe-indent
	ess-eval-region-or-line-visibly-and-step
	ess-smart-S-assign
	ess-smart-comma
	ess-use-this-dir
	ess-yank
	forward-page
	indent-for-tab-command
	insert-char
	kill-region
	multiple-cursors-mode
	org-beginning-of-line
	org-end-of-line
	org-force-self-insert
	org-insert-heading-respect-content
	org-insert-todo-heading-respect-content
	org-kill-line
	org-self-insert-command
	org-shiftleft
	org-shiftright
	python-shell-send-buffer
	transpose-words
	))

(setq mc/cmds-to-run-once
      '(
	dired-find-file
	goto-line
	helm-find
	mark-page
	mouse-set-region
	swiper
	))
